version: "3.3"
services:
  mysql:
    image: mysql:latest
    hostname: mysql
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: chat
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chat
  mysql2:
    image: mysql:latest
    hostname: mysql
    ports:
      - "3307:3306"
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
